---

# Site specific changes for F5 Ansible docker compose
#
# Configuration:
#
#   F5'ers, by changing the provided 'image' keys below, you can
#   use docker-compose to pull the F5 site images. This file should
#   be renamed to `docker-compose.site.yaml to take effect.
#
#   For example, change the following
#
#     f5ansible/py2.7-bare:devel
#
#   so-as to prepend the name of the docker registry
#
#     foo.f5.com/f5ansible/py2.7-bare:devel
#
#   Replace `foo.f5.com` with the actual docker registry name.
#
# Usage:
#
#   Rename this file to be docker-compose.site.yaml
#
#   The `docker-compose.site.yaml` file will be used automatically
#   by the tools packaged in this repository. If this file does
#   not exist, it will be skipped.
#

version: '3.3'
services:
  py2.7:
    image: f5ansible/py2.7:devel
  py2.7-bare:
    image: f5ansible/py2.7-bare:devel
  py3.5:
    image: f5ansible/py3.5:devel
  py3.5-bare:
    image: f5ansible/py3.5-bare:devel
  py3.6:
    image: f5ansible/py3.6:devel
  py3.6-bare:
    image: f5ansible/py3.6-bare:devel
